### ISSUE TITLE
[Not a Bug] Tied-up creature & Helpless

### ISSUE THREAD

**Issue by ZeliasC** [YLMstring/Prestige-Plus#65]
I've had some fun trying out the White Haired Witch, but I was puzzled that I couldn't move after tying up an enemy. The tabletop grappling rules are convoluted, but my understanding as a DM and player, is that once a creature is tied up, it doesn't require that you keep grappling it and you can perform other actions instead. Would have been nice to be able to move or grapple a second target after the first one is properly bound. Because as it is, the Witch can't do anything else but do low damage to its tied-up prey until somebody come help her kill it... or release it and waste all the efforts.

Also, there has been long debates whether tied up also means helpless, but I still think it would be a good feature to allowed a tied-up enemy to be coup de graced.

**Comment by YLMstring** [comment]
There are 3 kinds of grapples in the game. My Grapple Mechanic is very close to tabletop. Shifter and beast shape grapples stay owlcat-brew but once the character takes Grapple (Improved Grapple) feat, their grapple mechanics would be turned into mine. Finally, monster grapples stay the way it is in vanilla.
If you are grappled, you can attempt to break the grapple by making a combat maneuver check (DC equal to your opponent’s CMD; this does not provoke an attack of opportunity) or Thievery check (with a DC equal to your opponent’s CMD). If you succeed, you break the grapple as a standard action. However, if you fail nothing happens, you don't use your standard action.
You can only tie up pinned creatures, and then they still need to be grappled. The rope would be bursted if you release grapple, because you don't have time to tie someone up properly in combat. They are not helpless but can become the target of Coup De Grace. Additionally, grapple actions against them auto-succeed, they're auto pinned by the rope and their Thievery check DC to escape is higher.

**Comment by YLMstring** [comment]
So they should become valid target of a coup de grace
That's probably the only change I put on the github page rather than in-game descriptions :p
